// This file was generated by Prisma, and assumes you have installed the following:
// pnpm install --save-dev prisma dotenv
import { defineConfig } from 'prisma/config'
import 'dotenv/config'

export default defineConfig({
  schema: 'prisma/schema.prisma',
  datasource: {
    url: process.env.DIRECT_URL,
  },
})